// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });
config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Schema changes must use a direct/session connection. The application
    // runtime can independently use Supavisor transaction mode through
    // DATABASE_URL when deployed to Vercel.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
