import type { CurrentAdmin } from '@/lib/authorization';
import { createZionBrandedTablePdf, type ZionPdfColumn } from '@/lib/zion-pdf-export';
import { createCsv } from '@/lib/export/csv';
import { createXlsx } from '@/lib/export/spreadsheet';
import { datedExportFilename } from '@/lib/export/response';
import type { ExportColumn, ExportResult, ExportScope, ExportSheet } from '@/lib/export/types';
import type { ContractDto, ContractSummaryDto } from '@/services/contract';

const CONTRACT_COLUMNS: Array<ExportColumn<ContractDto>> = [
  { header: 'Contract ID', key: 'id', width: 28, value: (contract) => contract.id },
  { header: 'Contract Reference', key: 'contractNumber', width: 28, value: (contract) => contract.contractNumber },
  { header: 'Booking Reference', key: 'bookingReference', width: 24, value: (contract) => contract.bookingReference },
  { header: 'Client Name', key: 'clientName', width: 28, value: (contract) => contract.clientName },
  { header: 'Event Category', key: 'eventType', width: 24, value: (contract) => contract.eventType },
  { header: 'Event Date', key: 'eventDate', type: 'date', width: 18, value: (contract) => toDate(contract.eventDate) },
  { header: 'Package', key: 'packageName', width: 28, value: (contract) => contract.packageName },
  { header: 'Contract Status', key: 'contractStatus', width: 22, value: (contract) => formatEnum(contract.contractStatus) },
  { header: 'Email Status', key: 'emailStatus', width: 20, value: (contract) => formatEnum(contract.emailStatus) },
  { header: 'Workflow Status', key: 'workflowStatus', width: 24, value: (contract) => formatEnum(contract.workflowStatus) },
  { header: 'Signature Status', key: 'signatureStatus', width: 24, value: (contract) => formatEnum(contract.signatureStatus) },
  { header: 'Generated Date', key: 'createdAt', type: 'datetime', width: 22, value: (contract) => toDate(contract.createdAt) },
  { header: 'Sent Date', key: 'lastSentAt', type: 'datetime', width: 22, value: (contract) => toDate(contract.lastSentAt) },
  { header: 'Signed Date', key: 'signedAt', type: 'datetime', width: 22, value: (contract) => toDate(contract.signedAt) },
  { header: 'Expiration Date', key: 'expirationDate', width: 22, value: () => '' },
  { header: 'Last Updated', key: 'updatedAt', type: 'datetime', width: 22, value: (contract) => toDate(contract.updatedAt) },
  { header: 'Managed By', key: 'managedBy', width: 28, value: (contract) => contract.generatedBy ?? contract.sentBy ?? '' },
  { header: 'Contract Amount', key: 'contractAmount', type: 'currency', width: 18, value: (contract) => contract.contractAmount ?? 0 },
  { header: 'Total Paid', key: 'totalPaid', type: 'currency', width: 18, value: (contract) => contract.totalPaid ?? 0 },
  { header: 'Remaining Balance', key: 'remainingBalance', type: 'currency', width: 18, value: (contract) => contract.remainingBalance ?? 0 },
];

function toDate(value: Date | string | null | undefined) {
  if (!value) return null;
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function formatDateTime(value: Date | string | null | undefined, timeZone?: string) {
  const date = toDate(value);
  if (!date) return '';

  if (!timeZone) {
    return date.toISOString();
  }

  try {
    return new Intl.DateTimeFormat('en-PH', {
      dateStyle: 'medium',
      timeStyle: 'short',
      timeZone,
    }).format(date);
  } catch {
    return date.toISOString();
  }
}

function formatEnum(value: string | null | undefined) {
  return value
    ? value.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase())
    : 'Not Sent';
}

function money(value: number | null | undefined) {
  return `PHP ${(value ?? 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function createContractXlsx(input: {
  contracts: ContractDto[];
  failedDelivery: ContractDto[];
  signedContracts: ContractDto[];
  summary: ContractSummaryDto;
  searchParams: URLSearchParams;
  scope: ExportScope;
  actor: CurrentAdmin;
  timeZone?: string;
}) {
  const summary = input.summary;
  const summaryRows = [
    ['Zion Events Place - Contract Registry Export'],
    ['Generated At', formatDateTime(new Date(), input.timeZone)],
    ['Generated By', input.actor.fullName || input.actor.email],
    ['Scope', input.scope],
    ['Total Contracts', summary.totalContracts],
    ['Draft Contracts', summary.draftContracts],
    ['Ready To Send', summary.readyToSend],
    ['Sent Contracts', summary.sentContracts],
    ['Signed Contracts', summary.signedContracts],
    ['Failed Delivery', summary.failedDelivery],
    ['Bookings Without Contract', summary.bookingsWithoutContract],
    ['Pending Client Signature', summary.pendingClientSignature],
  ];
  const rowsFor = (contracts: ContractDto[]) => contracts.map((contract) => (
    CONTRACT_COLUMNS.map((column) => column.value(contract))
  ));
  const filterRows = Array.from(input.searchParams.entries())
    .filter(([key]) => !['format', 'timeZone'].includes(key))
    .map(([key, value]) => [key, value]);
  const registryColumns = CONTRACT_COLUMNS.map((column) => ({
    header: column.header,
    width: column.width,
    type: column.type,
  }));
  const sheets: ExportSheet[] = [
    { name: 'Summary', rows: summaryRows },
    { name: 'Contract Registry', columns: registryColumns, rows: rowsFor(input.contracts), freezeHeader: true },
    { name: 'Delivery Status', columns: registryColumns, rows: rowsFor(input.failedDelivery), freezeHeader: true },
    { name: 'Signed Contracts', columns: registryColumns, rows: rowsFor(input.signedContracts), freezeHeader: true },
    {
      name: 'Applied Filters',
      columns: [
        { header: 'Filter', width: 28 },
        { header: 'Value', width: 48 },
      ],
      rows: filterRows.length ? filterRows : [['None', 'No filters applied']],
      freezeHeader: true,
    },
  ];

  return createXlsx(sheets);
}

function createContractPdf(contracts: ContractDto[], timeZone?: string) {
  const columns: Array<ZionPdfColumn<ContractDto>> = [
    { header: 'Contract', width: 88, maxLines: 3, value: (contract) => contract.contractNumber },
    {
      header: 'Booking',
      width: 88,
      maxLines: 3,
      value: (contract) => `${contract.bookingReference} | ${contract.eventType}`,
    },
    {
      header: 'Client',
      width: 92,
      maxLines: 3,
      value: (contract) => [contract.clientName, contract.clientEmail ?? ''].filter(Boolean).join(' | '),
    },
    {
      header: 'Status',
      width: 88,
      align: 'center',
      maxLines: 3,
      value: (contract) => [
        formatEnum(contract.contractStatus),
        formatEnum(contract.signatureStatus),
      ].join(' | '),
    },
    {
      header: 'Dates',
      width: 92,
      maxLines: 4,
      value: (contract) => [
        `Event: ${formatDateTime(contract.eventDate, timeZone)}`,
        contract.lastSentAt ? `Sent: ${formatDateTime(contract.lastSentAt, timeZone)}` : '',
        contract.signedAt ? `Signed: ${formatDateTime(contract.signedAt, timeZone)}` : '',
      ].filter(Boolean).join(' | '),
    },
    {
      header: 'Financials',
      width: 108,
      maxLines: 4,
      value: (contract) => [
        `Amount: ${money(contract.contractAmount)}`,
        `Paid: ${money(contract.totalPaid)}`,
        `Balance: ${money(contract.remainingBalance)}`,
      ].join(' | '),
    },
  ];

  return createZionBrandedTablePdf({
    title: 'Contract Registry',
    subtitle: 'A branded legal operations export from Contract Management.',
    badge: 'Contract Registry',
    generatedAt: formatDateTime(new Date(), timeZone),
    recordCount: contracts.length,
    rows: contracts,
    columns,
    emptyMessage: 'No contract records matched the selected export scope.',
    footerLabel: 'Confidential contract registry export - Zion Events Place',
  });
}

export function createContractExportResult(
  format: 'csv' | 'excel' | 'pdf',
  input: {
    contracts: ContractDto[];
    failedDelivery: ContractDto[];
    signedContracts: ContractDto[];
    summary: ContractSummaryDto;
    searchParams: URLSearchParams;
    scope: ExportScope;
    actor: CurrentAdmin;
    timeZone?: string;
    limitApplied?: boolean;
  },
): ExportResult {
  if (format === 'csv') {
    return {
      body: createCsv(CONTRACT_COLUMNS, input.contracts),
      contentType: 'text/csv; charset=utf-8',
      filename: datedExportFilename('zion-contract-registry', 'csv'),
      exportedRecords: input.contracts.length,
      limitApplied: input.limitApplied,
    };
  }

  if (format === 'excel') {
    return {
      body: createContractXlsx(input),
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      filename: datedExportFilename('zion-contract-registry', 'xlsx'),
      exportedRecords: input.contracts.length,
      limitApplied: input.limitApplied,
    };
  }

  return {
    body: createContractPdf(input.contracts, input.timeZone),
    contentType: 'application/pdf',
    filename: datedExportFilename('zion-contract-registry', 'pdf'),
    exportedRecords: input.contracts.length,
    limitApplied: input.limitApplied,
  };
}

