import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { createZionBrandedTablePdf } from '../zion-pdf-export';
import { createCsv, safeExportText } from './csv';
import { idsFromSearchParams, normalizeExportIds } from './request';
import { createXlsx } from './spreadsheet';

describe('CSV exports', () => {
  it('quotes cells, uses CRLF rows, and protects formula-like values', () => {
    const csv = createCsv([
      { header: 'Client', key: 'client', value: (row: { client: string }) => row.client },
      { header: 'Notes', key: 'notes', value: (row: { notes: string }) => row.notes },
      { header: 'Balance', key: 'balance', value: (row: { balance: number }) => row.balance },
    ], [
      { client: '=SUM(A1:A2)', notes: 'He said "hello"', balance: -500 },
      { client: 'Maria Cruz', notes: 'Line one\nLine two', balance: 1200 },
    ]);

    assert.equal(csv, [
      '"ZION EVENTS PLACE EXPORT","",""',
      '"[ CIRCULAR ZION LOGO MEDALLION ]","",""',
      '"Charcoal #1a1f18 | Gold #D6B53B | Cream #FDF5CC","",""',
      '"","",""',
      '"Client","Notes","Balance"',
      '"\'=SUM(A1:A2)","He said ""hello""","\'-500"',
      '"Maria Cruz","Line one\nLine two","1200"',
    ].join('\r\n'));
  });

  it('guards every configured CSV injection prefix', () => {
    for (const value of ['=cmd', '+cmd', '-cmd', '@cmd', '\tcmd', '\rcmd']) {
      assert.equal(safeExportText(value), `'${value}`);
    }
  });
});

describe('Export request helpers', () => {
  it('dedupes and trims selected export IDs', () => {
    assert.deepEqual(normalizeExportIds([' booking-1 ', 'booking-1', '', 12, 'booking-2']), [
      'booking-1',
      'booking-2',
    ]);
    assert.deepEqual(idsFromSearchParams(new URLSearchParams('ids=a,b,a,%20c%20')), ['a', 'b', 'c']);
  });
});

describe('XLSX exports', () => {
  it('creates a workbook with sheets, filters, frozen headers, and typed cells', () => {
    const workbook = createXlsx([
      {
        name: 'Summary',
        rows: [['Generated By', 'Zion Super Admin']],
      },
      {
        name: 'Transactions',
        columns: [
          { header: 'Reference', width: 20 },
          { header: 'Amount', type: 'currency', width: 16 },
          { header: 'Paid At', type: 'datetime', width: 20 },
          { header: 'External Formula Text', width: 28 },
        ],
        rows: [[
          'PAY-001',
          1234.5,
          new Date('2026-07-09T04:00:00.000Z'),
          '@external',
        ]],
        freezeHeader: true,
      },
    ]);
    const bytes = Buffer.from(workbook);
    const text = bytes.toString('utf8');

    assert.equal(bytes.subarray(0, 2).toString('utf8'), 'PK');
    assert.match(text, /<sheet name="Summary"/);
    assert.match(text, /<sheet name="Transactions"/);
    assert.match(text, /xl\/media\/zionlogo\.(?:png|jpg)/);
    assert.match(text, /Zion circular medallion/);
    assert.match(text, /<drawing r:id="rId1"\/>/);
    assert.match(text, /<pane ySplit="1" topLeftCell="A2"/);
    assert.match(text, /<autoFilter ref="A1:D2"\/>/);
    assert.match(text, /<c r="B2" s="4"><v>1234.5<\/v><\/c>/);
    assert.match(text, /<c r="C2" s="7"><v>\d+(?:\.\d+)?<\/v><\/c>/);
    assert.match(text, /<t xml:space="preserve">&apos;@external<\/t>/);
  });
});

describe('PDF exports', () => {
  it('creates a paginated Zion-branded PDF without placeholder values', () => {
    const rows = Array.from({ length: 80 }, (_, index) => ({
      reference: `BKG-${String(index + 1).padStart(4, '0')}`,
      client: `Client ${index + 1}`,
      status: index % 2 === 0 ? 'Confirmed' : 'Pending',
    }));
    const pdf = createZionBrandedTablePdf({
      title: 'Booking Operations Schedule',
      subtitle: 'Automated export QA sample.',
      badge: 'Booking Management',
      generatedAt: 'Jul 9, 2026, 12:00 PM',
      recordCount: rows.length,
      rows,
      columns: [
        { header: 'Reference', width: 140, value: (row) => row.reference },
        { header: 'Client', width: 260, value: (row) => row.client },
        { header: 'Status', width: 156, value: (row) => row.status },
      ],
    });
    const text = Buffer.from(pdf).toString('latin1');

    assert.equal(text.slice(0, 8), '%PDF-1.4');
    assert.match(text, /ZION EVENTS PLACE/);
    assert.match(text, /\/Logo Do/);
    assert.match(text, /Page 2 of/);
    assert.doesNotMatch(text, /\bundefined\b|\bnull\b/);
  });
});
