import type { CurrentAdmin } from '@/lib/authorization';
import type { getReportsData } from '@/lib/reports-service';
import { createZionBrandedTablePdf, type ZionPdfColumn } from '@/lib/zion-pdf-export';
import { createCsv } from '@/lib/export/csv';
import { createXlsx } from '@/lib/export/spreadsheet';
import { datedExportFilename } from '@/lib/export/response';
import type { ExportColumn, ExportResult, ExportSheet } from '@/lib/export/types';

type ReportsData = Awaited<ReturnType<typeof getReportsData>>;
type MonthlyReportRow = ReportsData['monthly'][number];
type MetricRow = {
  metric: string;
  value: string | number;
};
type DistributionRow = {
  category: string;
  name: string;
  count: number;
};

const MONTHLY_COLUMNS: Array<ExportColumn<MonthlyReportRow>> = [
  { header: 'Month', key: 'label', width: 16, value: (row) => row.label },
  { header: 'Bookings', key: 'bookings', type: 'number', width: 14, value: (row) => row.bookings },
  { header: 'Pending Bookings', key: 'pending', type: 'number', width: 18, value: (row) => row.pending },
  { header: 'Confirmed Bookings', key: 'confirmed', type: 'number', width: 20, value: (row) => row.confirmed },
  { header: 'Revenue Collected', key: 'revenue', type: 'currency', width: 20, value: (row) => row.revenue },
  { header: 'Inquiries', key: 'inquiries', type: 'number', width: 14, value: (row) => row.inquiries },
  { header: 'Converted Inquiries', key: 'convertedInquiries', type: 'number', width: 20, value: (row) => row.convertedInquiries },
];

const METRIC_COLUMNS: Array<ExportColumn<MetricRow>> = [
  { header: 'Metric', key: 'metric', width: 34, value: (row) => row.metric },
  { header: 'Value', key: 'value', width: 22, value: (row) => row.value },
];

const DISTRIBUTION_COLUMNS: Array<ExportColumn<DistributionRow>> = [
  { header: 'Category', key: 'category', width: 28, value: (row) => row.category },
  { header: 'Name', key: 'name', width: 38, value: (row) => row.name },
  { header: 'Count', key: 'count', type: 'number', width: 14, value: (row) => row.count },
];

function formatDateTime(value: Date | string, timeZone?: string) {
  const date = value instanceof Date ? value : new Date(value);

  if (Number.isNaN(date.getTime())) {
    return '';
  }

  if (!timeZone) {
    return date.toISOString();
  }

  try {
    return new Intl.DateTimeFormat('en-PH', {
      dateStyle: 'medium',
      timeStyle: 'short',
      timeZone,
    }).format(date);
  } catch {
    return date.toISOString();
  }
}

function money(value: number) {
  return `PHP ${value.toLocaleString('en-PH', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function metricRows(data: ReportsData): MetricRow[] {
  return [
    { metric: 'Booking Count', value: data.summary.bookingCount },
    { metric: 'Pending Booking Count', value: data.summary.pendingBookingCount },
    { metric: 'Revenue Collected', value: data.summary.revenueCollected },
    { metric: 'Revenue Forecast', value: data.summary.revenueForecast },
    { metric: 'Pending Payment Count', value: data.summary.pendingPaymentCount },
    { metric: 'Pending Payment Balance', value: data.summary.pendingPaymentBalance },
    { metric: 'Inquiry Count', value: data.summary.inquiryCount },
    { metric: 'Inquiry Conversion Rate', value: `${data.summary.inquiryConversionRate.toFixed(1)}%` },
    { metric: 'Average Inquiry Response Hours', value: Number(data.summary.averageInquiryResponseHours.toFixed(1)) },
    { metric: 'Unanswered Inquiry Count', value: data.summary.unansweredInquiryCount },
    { metric: 'Follow-up Inquiry Count', value: data.summary.followUpInquiryCount },
  ];
}

function distributionRows(data: ReportsData): DistributionRow[] {
  return [
    ...data.eventTypes.map((row) => ({ category: 'Event Type', ...row })),
    ...data.packages.map((row) => ({ category: 'Package', ...row })),
    ...data.inquiryEventInterests.map((row) => ({ category: 'Inquiry Interest', ...row })),
  ];
}

function createReportsCsv(data: ReportsData, dataset: string) {
  if (dataset === 'metrics') {
    return createCsv(METRIC_COLUMNS, metricRows(data));
  }

  if (dataset === 'categories') {
    return createCsv(DISTRIBUTION_COLUMNS, distributionRows(data));
  }

  return createCsv(MONTHLY_COLUMNS, data.monthly);
}

function createReportsXlsx(data: ReportsData, actor: CurrentAdmin, timeZone?: string) {
  const metrics = metricRows(data);
  const distributions = distributionRows(data);
  const sheets: ExportSheet[] = [
    {
      name: 'Executive Summary',
      rows: [
        ['Zion Events Place - Reports & Analytics Export'],
        ['Generated At', formatDateTime(new Date(), timeZone)],
        ['Generated By', actor.fullName || actor.email],
        [],
        ...metrics.map((row) => [row.metric, row.value]),
      ],
    },
    {
      name: 'Monthly Breakdown',
      columns: MONTHLY_COLUMNS.map((column) => ({
        header: column.header,
        width: column.width,
        type: column.type,
      })),
      rows: data.monthly.map((row) => MONTHLY_COLUMNS.map((column) => column.value(row))),
      freezeHeader: true,
    },
    {
      name: 'Revenue',
      columns: [
        { header: 'Month', width: 16 },
        { header: 'Revenue Collected', width: 20, type: 'currency' },
        { header: 'Bookings', width: 14, type: 'number' },
      ],
      rows: data.monthly.map((row) => [row.label, row.revenue, row.bookings]),
      freezeHeader: true,
    },
    {
      name: 'Bookings',
      columns: [
        { header: 'Month', width: 16 },
        { header: 'Pending', width: 14, type: 'number' },
        { header: 'Confirmed', width: 14, type: 'number' },
        { header: 'Total', width: 14, type: 'number' },
      ],
      rows: data.monthly.map((row) => [row.label, row.pending, row.confirmed, row.bookings]),
      freezeHeader: true,
    },
    {
      name: 'Payments',
      columns: [
        { header: 'Metric', width: 34 },
        { header: 'Value', width: 22, type: 'currency' },
      ],
      rows: [
        ['Revenue Collected', data.summary.revenueCollected],
        ['Revenue Forecast', data.summary.revenueForecast],
        ['Pending Payment Balance', data.summary.pendingPaymentBalance],
      ],
      freezeHeader: true,
    },
    {
      name: 'Categories',
      columns: DISTRIBUTION_COLUMNS.map((column) => ({
        header: column.header,
        width: column.width,
        type: column.type,
      })),
      rows: distributions.map((row) => DISTRIBUTION_COLUMNS.map((column) => column.value(row))),
      freezeHeader: true,
    },
    {
      name: 'Applied Filters',
      columns: [
        { header: 'Filter', width: 28 },
        { header: 'Value', width: 48 },
      ],
      rows: [['Range', 'Last 6 months'], ['Report Source', 'Reports & Analytics dashboard data']],
      freezeHeader: true,
    },
  ];

  return createXlsx(sheets);
}

function createReportsPdf(data: ReportsData, actor: CurrentAdmin, timeZone?: string) {
  const rows = [
    ...metricRows(data).map((row) => ({
      section: 'KPI',
      label: row.metric,
      value: typeof row.value === 'number' && row.metric.toLowerCase().includes('revenue')
        ? money(row.value)
        : String(row.value),
    })),
    ...data.monthly.map((row) => ({
      section: 'Monthly',
      label: row.label,
      value: `${row.bookings} bookings | ${money(row.revenue)} collected | ${row.inquiries} inquiries`,
    })),
    ...distributionRows(data).slice(0, 18).map((row) => ({
      section: row.category,
      label: row.name,
      value: `${row.count} record(s)`,
    })),
  ];
  const columns: Array<ZionPdfColumn<(typeof rows)[number]>> = [
    { header: 'Section', width: 86, maxLines: 2, value: (row) => row.section },
    { header: 'Metric', width: 178, maxLines: 3, value: (row) => row.label },
    { header: 'Value', width: 292, maxLines: 4, value: (row) => row.value },
  ];

  return createZionBrandedTablePdf({
    title: 'Executive Report',
    subtitle: 'A branded analytics export calculated from inquiry, booking, contract, and payment records.',
    badge: 'Reports & Analytics',
    generatedAt: `${formatDateTime(new Date(), timeZone)} | ${actor.fullName || actor.email}`,
    recordCount: rows.length,
    rows,
    columns,
    emptyMessage: 'No report data is available for the selected range.',
    footerLabel: 'Confidential reports and analytics export - Zion Events Place',
  });
}

export function createReportsExportResult(
  format: 'csv' | 'excel' | 'pdf',
  data: ReportsData,
  actor: CurrentAdmin,
  timeZone?: string,
  dataset = 'monthly',
): ExportResult {
  if (format === 'csv') {
    return {
      body: createReportsCsv(data, dataset),
      contentType: 'text/csv; charset=utf-8',
      filename: datedExportFilename(`zion-reports-${dataset}`, 'csv'),
      exportedRecords: dataset === 'metrics'
        ? metricRows(data).length
        : dataset === 'categories'
        ? distributionRows(data).length
        : data.monthly.length,
    };
  }

  if (format === 'excel') {
    return {
      body: createReportsXlsx(data, actor, timeZone),
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      filename: datedExportFilename('zion-reports-analytics', 'xlsx'),
      exportedRecords: data.monthly.length,
    };
  }

  return {
    body: createReportsPdf(data, actor, timeZone),
    contentType: 'application/pdf',
    filename: datedExportFilename('zion-executive-report', 'pdf'),
    exportedRecords: data.monthly.length,
  };
}

