'use client';

import React from 'react';

const pendingContracts = [
  { client: 'Mark & Julia', type: 'Wedding Contract', time: 'Today', status: 'Needs Approval', statusColor: 'bg-orange-100 text-orange-700' },
  { client: 'Company XMAS', type: 'Event Agreement', time: 'Yesterday', status: 'Email Failed', statusColor: 'bg-pink-100 text-pink-700' },
  { client: 'Alice & Bob', type: 'Wedding Contract', time: '2 days ago', status: 'Needs Approval', statusColor: 'bg-orange-100 text-orange-700' },
];

export default function ContractManagement() {
  return (
    <div className="flex gap-6 h-full font-serif text-[#1a1f18]">
      
      {/* Left Sidebar - Pending Contracts */}
      <div className="w-[380px] bg-white rounded-xl shadow-sm border border-black/5 overflow-hidden flex flex-col h-full">
        {/* Header */}
        <div className="bg-[#FDF5CC] p-5 border-b border-black/5">
          <h2 className="text-xl font-bold">Pending Contracts</h2>
          <p className="text-xs text-gray-500 mt-1">Awaiting admin approval or fallback action</p>
        </div>

        {/* List */}
        <div className="flex-1 overflow-y-auto">
          <div className="divide-y divide-gray-100">
            {pendingContracts.map((contract, idx) => (
              <div key={idx} className="p-5 hover:bg-gray-50 cursor-pointer transition-colors relative group">
                <div className="flex justify-between items-start mb-1">
                  <h3 className="font-bold text-[#1a1f18] group-hover:text-[#BCA63B] transition-colors">{contract.client}</h3>
                  <span className="text-xs text-gray-400">{contract.time}</span>
                </div>
                <p className="text-sm text-gray-500 mb-3">{contract.type}</p>
                <span className={`inline-flex px-3 py-1 text-[10px] font-bold uppercase rounded-full tracking-wider ${contract.statusColor}`}>
                  {contract.status}
                </span>
                
                {/* Active Selection Indicator */}
                {idx === 0 && (
                  <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-[#BCA63B]" />
                )}
              </div>
            ))}
          </div>
        </div>
        
        {/* Bottom Filler to match design height styling */}
        <div className="h-40 bg-[#FDF5CC]/50 mt-auto border-t border-black/5"></div>
      </div>

      {/* Right Content - Document Viewer */}
      <div className="flex-1 bg-[#FDF5CC] rounded-xl p-6 shadow-sm border border-black/5 flex flex-col relative h-full">
        
        {/* Header Toolbar */}
        <div className="flex justify-between items-center mb-6">
          <div>
            <h2 className="text-2xl font-bold">Mickey & Minnie - Wedding Contract</h2>
            <p className="text-sm text-gray-500">Auto-generated by n8n workflow</p>
          </div>
          <button className="bg-[#9df3b6] hover:bg-[#85eba2] text-[#1a1f18] px-6 py-2.5 rounded-lg font-bold text-sm shadow-sm transition-colors border border-green-300">
            Approve & Send
          </button>
        </div>

        {/* Document Preview */}
        <div className="flex-1 bg-white rounded-lg shadow-inner overflow-y-auto p-12 relative border border-gray-200">
          
          {/* Watermark */}
          <div className="absolute inset-0 pointer-events-none flex items-center justify-center opacity-[0.04] overflow-hidden">
            <span className="text-[150px] font-bold transform -rotate-45 tracking-widest whitespace-nowrap">
              UNAPPROVED
            </span>
          </div>

          <div className="max-w-3xl mx-auto">
            {/* Doc Header */}
            <div className="text-center mb-12 border-b-2 border-[#1a1f18]/10 pb-8">
              <h1 className="text-3xl font-serif font-bold tracking-widest text-[#1a365d] mb-2">ZENTRA EVENTS</h1>
              <p className="text-sm font-semibold text-gray-500 tracking-widest uppercase">Service Agreement</p>
            </div>

            {/* Client Details */}
            <div className="space-y-4 mb-12">
              <p><strong className="text-gray-800">Date of Agreement:</strong> June 18, 2026</p>
              <p><strong className="text-gray-800">Client Names:</strong> Mark & Julia</p>
              <p><strong className="text-gray-800">Event Type:</strong> Wedding Reception</p>
              <p><strong className="text-gray-800">Package Selected:</strong> Premium 150Pax</p>
              <p><strong className="text-gray-800">Total Amount Due:</strong> ₱350,000.00</p>
            </div>

            {/* Terms Content */}
            <div className="space-y-8 text-sm leading-relaxed text-gray-700">
              <div>
                <h3 className="font-bold text-base text-black mb-2">1. Payment Terms</h3>
                <p>A 50% downpayment is required upon signing this agreement to secure the date. The remaining balance must be settled in full no later than one (1) week prior to the event date. Failure to meet these deadlines may result in the forfeiture of the reserved date.</p>
              </div>
              
              <div>
                <h3 className="font-bold text-base text-black mb-2">2. Cancellation Policy</h3>
                <p>Cancellations made within 30 days of the event date will result in full forfeiture of the downpayment. In the event of force majeure, ZENTRA management will evaluate rescheduling options subject to availability.</p>
              </div>
            </div>
          </div>
        </div>

        {/* Fallback Options Footer */}
        <div className="mt-6">
          <p className="text-sm font-medium text-[#1a1f18]/70 mb-3">Delivery Fallback Options</p>
          <div className="flex gap-4">
            <button className="flex-1 bg-white hover:bg-gray-50 border border-gray-200 text-[#1a1f18] py-3 rounded-lg font-bold text-sm shadow-sm transition-colors text-center">
              Download PDF
            </button>
            <button className="flex-1 bg-white hover:bg-gray-50 border border-gray-200 text-[#1a1f18] py-3 rounded-lg font-bold text-sm shadow-sm transition-colors text-center flex items-center justify-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4"><path strokeLinecap="round" strokeLinejoin="round" d="M13.19 8.688a4.5 4.5 0 0 1 1.242 7.244l-4.5 4.5a4.5 4.5 0 0 1-6.364-6.364l1.757-1.757m13.35-.622 1.757-1.757a4.5 4.5 0 0 0-6.364-6.364l-4.5 4.5a4.5 4.5 0 0 0 1.242 7.244" /></svg>
              Generate Shareable Link
            </button>
            <button className="flex-1 bg-white hover:bg-gray-50 border border-gray-200 text-[#1a1f18] py-3 rounded-lg font-bold text-sm shadow-sm transition-colors text-center flex items-center justify-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-4 h-4"><path d="M3.478 2.404a.75.75 0 0 0-.926.941l2.432 7.905H13.5a.75.75 0 0 1 0 1.5H4.984l-2.432 7.905a.75.75 0 0 0 .926.94 60.519 60.519 0 0 0 18.445-8.986.75.75 0 0 0 0-1.218A60.517 60.517 0 0 0 3.478 2.404Z" /></svg>
              Resend Email
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
